### PR TITLE
Building with rake

### PR DESCRIPTION
**Pull request by haf**
Hello Krzysztof,

Here is a pull request. It contains a rakefile with albacore and nuget building tasks for Windsor and all the small projects, too. Tell me what you think!

Cheers,
Henrik

### CODE REVIEW

**Comment by tkellogg** [comment]
@haf - nice setup! I was never a big fan of MSBuild. My only concern is why you are maintaining version info in a ruby file instead of `AssemblyInfo.cs`

**Comment by hazzik** [comment]
It is the worst pull request I ever seen

**Comment by mausch** [comment]
Discussion here: http://groups.google.com/group/castle-project-devel/browse_thread/thread/e6ee9691228ec091

**Comment by hazzik** [comment]
Есть такой замечательный русский анекдот:
Сидит программист глубоко в отладке. Третий день сидит. Ничего не получается. Подходит к нему сынишка, и говорит:
- Папа, а почему солнце встает на востоке?
- Ты это проверял?
- Да.
- Работает?
- Да.
- Каждый день работает?
- Да.
- Тогда сынок, ради бога, ничего не трогай, ничего не меняй!

**Comment by haf** [comment]
Well Hazzik, with regards to your russian comment, it **does also** work with this pull request ^^ - but also **adds** functionality and makes it honestly a lot easier to read the scripts - try getting a really good grip on the msbuild scripts and then the rake scripts and measure the time taken for both... I bet you the rake scripts will get you there faster. :)

**Comment by hazzik** [comment]
If reading of msbuild is hard for you - it is your and only your problem. In addition, rake requres ruby to be installed in the environment, while msbuild already installed with .net fx.

**Comment by haf** [comment]
It's actually a problem for everyone who needs to read it and maintain it. XML was not meant to be executable ^^ and it's absurd we program in a non-programming language when we _are programmers_. In any way, the discussion has been linked to and I would urge you to continue debating your stance there. Thank you. **Hazzik, please use the mailing list.**

**Pull request closed without merging**
