### PR TITLE
Two bug fixes and one change

### PR DESCRIPTION
**Pull request by whut**
Bugfix 1: PerformanceMetricsFactory had inverted condition inside InitializedSuccessfully property and should also catch SecurityException while calling PerformanceCounterCategory.Create

Bugfix 2: one using statement missing in AbstractComponentActivator when compiling under .NET 3.5 or SL

Change: removed ILifecycleConcern interface, with it it is impossible to implement ICommissionConcern and IDecommissionConcern in single class (which I wanted to do:)). ILifecycleConcern had method Apply that had no meaning under this interface, instead it should be in ICommissionConcern and IDecommissionConcern separately.

### CODE REVIEW

**Comment by whut** [comment]
I'va added another fix: one test fails under .NET 3.5, because it uses .NET 2.0 version of CSharpCodeProvider, which does not support "var" keyword

**Comment by kkozmic** [comment]
Hi

thans for the fixes. As to ILifecycleConcern - what do you mean you can't implement both, commission and decommission in a single class - that's exactly what LateBoundConcerns is doing...

**Comment by whut** [comment]
I would like to write something like that:

class OnCommissionAndDecomsissionOfSomething : ICommisssionConcern, IDecommissionConcern
{
  void ICommisssionConcern.Apply()
  {
    // do something on commission
  }

  void IDecommissionConcern.Apply()
  {
    // do something on decommission
  }
}

But of course I can wrote that in two classes. Maybe it's only a matter of preference/taste, so I would not mind not merging b4a56cc :)

**Comment by kkozmic** [comment]
Ok,

That's a fair request and since that's going to be a major release we can afford a breaking change.

**Comment by whut** [comment]
Thanks!

**Pull request merged**
